/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemonstrationsAtelierVertRouteImport } from './routes/demonstrations.atelier-vert'
import { Route as DemonstrationsFluxPmeRouteImport } from './routes/demonstrations.flux-pme'
import { Route as DemonstrationsNovaRenovationRouteImport } from './routes/demonstrations.nova-renovation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstrationsAtelierVertRoute =
  DemonstrationsAtelierVertRouteImport.update({
    id: '/demonstrations/atelier-vert',
    path: '/demonstrations/atelier-vert',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemonstrationsFluxPmeRoute = DemonstrationsFluxPmeRouteImport.update({
  id: '/demonstrations/flux-pme',
  path: '/demonstrations/flux-pme',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstrationsNovaRenovationRoute =
  DemonstrationsNovaRenovationRouteImport.update({
    id: '/demonstrations/nova-renovation',
    path: '/demonstrations/nova-renovation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demonstrations/atelier-vert': typeof DemonstrationsAtelierVertRoute
  '/demonstrations/flux-pme': typeof DemonstrationsFluxPmeRoute
  '/demonstrations/nova-renovation': typeof DemonstrationsNovaRenovationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demonstrations/atelier-vert': typeof DemonstrationsAtelierVertRoute
  '/demonstrations/flux-pme': typeof DemonstrationsFluxPmeRoute
  '/demonstrations/nova-renovation': typeof DemonstrationsNovaRenovationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demonstrations/atelier-vert': typeof DemonstrationsAtelierVertRoute
  '/demonstrations/flux-pme': typeof DemonstrationsFluxPmeRoute
  '/demonstrations/nova-renovation': typeof DemonstrationsNovaRenovationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demonstrations/atelier-vert'
    | '/demonstrations/flux-pme'
    | '/demonstrations/nova-renovation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demonstrations/atelier-vert'
    | '/demonstrations/flux-pme'
    | '/demonstrations/nova-renovation'
  id:
    | '__root__'
    | '/'
    | '/demonstrations/atelier-vert'
    | '/demonstrations/flux-pme'
    | '/demonstrations/nova-renovation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemonstrationsAtelierVertRoute: typeof DemonstrationsAtelierVertRoute
  DemonstrationsFluxPmeRoute: typeof DemonstrationsFluxPmeRoute
  DemonstrationsNovaRenovationRoute: typeof DemonstrationsNovaRenovationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstrations/atelier-vert': {
      id: '/demonstrations/atelier-vert'
      path: '/demonstrations/atelier-vert'
      fullPath: '/demonstrations/atelier-vert'
      preLoaderRoute: typeof DemonstrationsAtelierVertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstrations/flux-pme': {
      id: '/demonstrations/flux-pme'
      path: '/demonstrations/flux-pme'
      fullPath: '/demonstrations/flux-pme'
      preLoaderRoute: typeof DemonstrationsFluxPmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstrations/nova-renovation': {
      id: '/demonstrations/nova-renovation'
      path: '/demonstrations/nova-renovation'
      fullPath: '/demonstrations/nova-renovation'
      preLoaderRoute: typeof DemonstrationsNovaRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemonstrationsAtelierVertRoute: DemonstrationsAtelierVertRoute,
  DemonstrationsFluxPmeRoute: DemonstrationsFluxPmeRoute,
  DemonstrationsNovaRenovationRoute: DemonstrationsNovaRenovationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
